### ISSUE TITLE
Understanding how sampling works

### ISSUE THREAD

**Issue by marcdel** [open-telemetry/opentelemetry-erlang#130]
I'm trying to understand how sampling works in the SDK, especially with regard to if/how the probability samplers cascade to child spans.

I've put together some test cases here: https://github.com/marcdel/otel_sandbox/tree/master/test

These are the tests that are failing because they exported a span when I expected them not to, or vice versa.
```
1) test percentage when parent is not set, and children are off, parent is exported but children are not (ParentChildTest)
2) test percentage when parent is off, but children are on: parent is not exported, but children are (ParentChildTest)
3) test percentage when parent is percentage, and children are not set: parent and children use percentage (ParentChildTest)
4) test percentage when parent is on, but children are off: parent is exported, children are not (ParentChildTest)
5) test always_on/off when parent is off, and children are not set: parent and children are not exported (ParentChildTest)
```

A simple example: if I specify a 0.0 sampler for the parent, which isn’t exported, I would expect the children not to be exported, but they are. For what it's worth, the on/off sampler behaves the same way in this case.

```
@zero_percent_sampler :ot_sampler.setup(:probability, %{probability: 0.0})

OpenTelemetry.Tracer.with_span "parent", %{sampler: @zero_percent_sampler} do
  Enum.map(1..4, fn i ->
    OpenTelemetry.Tracer.with_span "child#{i}" do
    end
  end)
end
```

The percentage based samplers seem to behave differently than the on/off samplers (when set to 100% or 0% respectively) in a few cases, which also seemed surprising.

On slack @tsloughter pointed out that this may have changed recently. I tried pointing this test repo to the master branch to see, but I get a compile error:
```
▶ mix test
===> Compiling opentelemetry
===> Compiling src/otel_metric_exporter.erl failed
src/otel_metric_exporter.erl:30: can't find include lib "opentelemetry_api/include/opentelemetry.hrl"; Make sure opentelemetry_api is in your app file's 'applications' list

** (Mix) Could not compile dependency :opentelemetry, "/Users/marc/.asdf/installs/elixir/1.10.3/.mix/rebar3 bare compile --paths="/Users/marc/Code/marcdel/otel_sandbox/_build/test/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile opentelemetry", update it with "mix deps.update opentelemetry" or clean it with "mix deps.clean opentelemetry"
```

**Comment by tsloughter** [comment]
Hm, are you only including the api as a dep? I'm surprised that this is failing. Can you show how you have the deps configured in mix.exs

**Comment by marcdel** [comment]
Sure. I tried with and without `tag: "master"`.

```
{:opentelemetry, github: "open-telemetry/opentelemetry-erlang", tag: "master", sparse: "apps/opentelemetry"},
{:opentelemetry_api, github: "open-telemetry/opentelemetry-erlang", tag: "master", sparse: "apps/opentelemetry_api"},
```

https://github.com/marcdel/otel_sandbox/blob/master/mix.exs#L25-L26

This bit is interesting
> Make sure opentelemetry_api is in your app file's 'applications' list

I tried adding to both applications and extra_applications, but no dice. I assume that an error from inside the opentelemetry app.
```
  def application do
    [
      applications: [:opentelemetry_api],
      extra_applications: [:logger, :opentelemetry_api],
      mod: {OtelSandbox.Application, []}
    ]
  end
```

**Comment by kw7oe** [comment]
I experience similar error while setting up a example for OpenTelemetry. The quick fix that I do is basically, manually compiling `opentelemtry_api` first by running `mix deps.compile opentelemetry_api`. Further details can be found [here](https://github.com/opentelemetry-beam/opentelemetry-examples/pull/6).

**Comment by tsloughter** [comment]
Thanks @kw7oe, this must be some oddity with git and sparse deps instead of hex package but I don't get why.

**Comment by marcdel** [comment]
Thanks, y'all. I got a little further, but now I get

```
Code/marcdel/otel_sandbox  master ✗                                                                                                                                                                                                  4h2m ⚑
▶ mix test
Compiling 2 files (.ex)
Generated otel_sandbox app

== Compilation error in file test/root_span_test.exs ==
** (RuntimeError) error parsing file /Users/marc/Code/marcdel/otel_sandbox/_build/test/lib/opentelemetry/include/ot_span.hrl, got: {:error, :enoent}
    (elixir 1.10.3) lib/record/extractor.ex:84: Record.Extractor.read_file/2
    (elixir 1.10.3) lib/record/extractor.ex:64: Record.Extractor.extract_all_records/1
    test/root_span_test.exs:10: (module)
    (stdlib 3.11.2) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.10.3) lib/kernel/parallel_compiler.ex:396: Kernel.ParallelCompiler.require_file/2
    (elixir 1.10.3) lib/kernel/parallel_compiler.ex:306: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

And if I comment out the `Record.extract_all(from_lib: "opentelemetry/include/ot_span.hrl")` and corresponding assertions I still get
```
Code/marcdel/otel_sandbox  master ✗                                                                                                                                                                                                 4h2m ⚑  ⍉
▶ mix test

== Compilation error in file test/root_span_test.exs ==
** (UndefinedFunctionError) function :ot_sampler.setup/2 is undefined (module :ot_sampler is not available)
    :ot_sampler.setup(:always_on, %{})
    test/root_span_test.exs:14: (module)
    (stdlib 3.11.2) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.10.3) lib/kernel/parallel_compiler.ex:396: Kernel.ParallelCompiler.require_file/2
    (elixir 1.10.3) lib/kernel/parallel_compiler.ex:306: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

**Comment by tsloughter** [comment]
Does `/Users/marc/Code/marcdel/otel_sandbox/_build/test/lib/opentelemetry/include/ot_span.hrl` exist?

**Comment by marcdel** [comment]
> Does `/Users/marc/Code/marcdel/otel_sandbox/_build/test/lib/opentelemetry/include/ot_span.hrl` exist?

Looks like yeah
![image](https://user-images.githubusercontent.com/693730/97623702-4e7cbb80-19e3-11eb-9e61-df9fc532d4ca.png)

**Comment by tsloughter** [comment]
Hey @marcdel I think the compilation errors are an issue with mix's path setting when calling rebar3 but have not confirmed yet.

I will get a new release of the apps to hex this weekend which will work.

The names of the samplers have changed but setting the probability to 0 or 100 should act like on/off and I will look into that first.

**Comment by marcdel** [comment]
Awesome, thanks man! I'll give it a go once it's available and let you know how it goes 🙂
